# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x04user\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"E\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Q\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"\x1c\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\"@\n\x0c\x41uthResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t2\xbd\x01\n\x0bUserService\x12=\n\x0cRegisterUser\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x12\x34\n\tLoginUser\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12\x39\n\x10\x41uthenticateUser\x12\x11.user.AuthRequest\x1a\x12.user.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=28
  _globals['_REGISTERREQUEST']._serialized_end=96
  _globals['_REGISTERRESPONSE']._serialized_start=98
  _globals['_REGISTERRESPONSE']._serialized_end=167
  _globals['_LOGINREQUEST']._serialized_start=169
  _globals['_LOGINREQUEST']._serialized_end=219
  _globals['_LOGINRESPONSE']._serialized_start=221
  _globals['_LOGINRESPONSE']._serialized_end=302
  _globals['_AUTHREQUEST']._serialized_start=304
  _globals['_AUTHREQUEST']._serialized_end=332
  _globals['_AUTHRESPONSE']._serialized_start=334
  _globals['_AUTHRESPONSE']._serialized_end=398
  _globals['_USERSERVICE']._serialized_start=401
  _globals['_USERSERVICE']._serialized_end=590
# @@protoc_insertion_point(module_scope)
